version: '2'
services:
    dockerui:
        image: uifd/ui-for-docker
        container_name: dockerui
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9000:9000
        restart: always
        privileged: true
            
    transmission:
        image: linuxserver/transmission
        container_name: transmission
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/transmission/config:/config
            - /media/nas/Transmission/Completed:/downloads
            - /media/nas/Transmission/Watch:/watch
            - /media/nas/Transmission/Incomplete:/incomplete
            - /media/nas/Video:/video
            - /media/nas/Music:/music
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: always
        environment:
            - PGID=1000
            - PUID=1000
            
    plex:
        image: linuxserver/plex
        container_name: plex
        network_mode: "host"
        volumes:
            - /docker/plex/config:/config
            - /docker/plex/transcode:/transcode
            - /media/nas/Transmission/Completed:/media/Completed
            - /media/nas/Video:/media/Video
            - /media/nas/Music:/media/Music
            - /media/nas/Album:/media/Album
        restart: always
        environment:
            - VERSION=latest
            - TZ=Europe/Minsk
            - PGID=1000
            - PUID=1000

    plexpy:
        image: linuxserver/plexpy
        container_name: plexpy
        volumes:
            - /docker/plexpy/config:/config
            - /docker/plex/config/Library/Application Support/Plex Media Server/Logs:/logs
        ports:
            - 8181:8181            
        restart: always
        environment:
            - TZ=Europe/Minsk
            - PGID=1000
            - PUID=1000            
            
    mariadb:
        image: linuxserver/mariadb 
        container_name: mariadb 
        volumes:
            - /docker/mariadb:/config
        ports:
            - 3306:3306
        restart: always
        environment:
            - PGID=1000
            - PUID=1000
            - MYSQL_ROOT_PASSWORD
            - TZ=Europe/Minsk
            
    tt-rss:
        image: linuxserver/tt-rss 
        container_name: tt-rss 
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/tt-rss:/config
        ports:
            - 9081:80
            - 9444:443
        links:
            - mariadb:db
        restart: always
        environment:
            - PGID=1000
            - PUID=1000
            - TZ=Europe/Minsk            

    muximux:
        image: linuxserver/muximux 
        container_name: muximux  
        volumes:
            - /docker/muximux:/config
            - /docker/tt-rss:/config
        ports:
            - 80:80
        restart: always
        environment:
            - PGID=1000
            - PUID=1000
            - TZ=Europe/Minsk  
            
    crashplan:
        image: jrcs/crashplan
        container_name: crashplan  
        volumes:
            - /docker/crashplan/config:/var/crashplan
            - /media/nas:/media/nas:ro
            - /media/nas/Backups/Crashplan:/storage
            - /docker:/media/docker:ro
            - /etc/systemd:/media/etc/systemd:ro
            - /etc/openvpn:/media/etc/openvpn:ro
            - /root/openvpn-ca:/media/root/openvpn-ca:ro
        ports:
            - 4242:4242
            - 4243:4243
        restart: always
        hostname: machine
        environment:
            - TZ=Europe/Minsk       
            
    unifi:
        image: linuxserver/unifi 
        container_name: unifi
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/unifi:/config
        ports:
            - 8080:8080
            - 8081:8081
            - 8443:8443 
            - 8843:8843
            - 8880:8880
        restart: always
        environment:
            - PGID=1000
            - PUID=1000
            - TZ=Europe/Minsk                 

    #sonarr:
    #    image: linuxserver/sonarr
    #    container_name: sonarr  
    #    volumes:
    #        - /docker/sonarr/config:/config
    #        - /dev/rtc:/dev/rtc:ro
    #        - /media/nas/Video/Зарубежные сериалы:/tv
    #        - /media/nas/Transmission/Completed:/downloads
    #    ports:
    #        - 8989:8989
    #    restart: always 
    #    environment:
    #        - PGID=1000
    #        - PUID=1000
    
    torrentmonitor:
        image: nawa/torrentmonitor
        container_name: torrentmonitor
        hostname: torrentmonitor
        volumes:
            - /docker/torrentmonitor:/data/htdocs/db
            - /media/nas/Transmission/Completed:/data/htdocs/torrents
            - /media/nas/Video:/media/Video
            - /media/nas/Music:/media/Music
        ports:
            - 9080:80/tcp
        restart: always
        links:
            - transmission
        environment:
            - CRON_TIMEOUT="0 * * * *"
            - PHP_TIMEZONE="Europe/Minsk"
            - PHP_MEMORY_LIMIT="512M"
            - TZ=Europe/Minsk      

    openhab:
        image: openhab/openhab:2.1.0-amd64-alpine
        container_name: openhab
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /docker/openhab/conf:/openhab/conf
            - /docker/openhab/userdata:/openhab/userdata
            - /docker/openhab/addons:/openhab/addons
            - /docker/openhab/.java:/openhab/.java
        network_mode: "host"
        restart: always
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        environment:
            - PGID=997
            - PUID=998
            - OPENHAB_HTTP_PORT=7080
            - OPENHAB_HTTPS_PORT=7443
            
            
            
            
